name: Snake animation

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build snake
        run: npx @anurag-hu/snake-github --colors 'DD2727,FFA500,00FF00,0000FF'

      - name: Commit and push if changes found
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --staged --quiet || git commit -m "Update README.md" && git push
